name: publish to ghcr.io
##REF:https://github.com/docker/login-action

env:
  MINISCRIPT_DOCKER: 'miniscript-docker'
  MINT_000_0: ''
  MINT_000_1: ''
  MINT_001_0: ''
  MINT_001_1: ''
  MINT_002_0: ''
  MINT_002_1: ''
  MINT_003_0: ''
  MINT_003_1: ''
  MINT_004_0: 'pk_h(mint004)'
  MINT_004_1: 'pk_h(mint004)'

on:
  push:
    branches:
      - master
      - main
      - v**
    tags:
      - v0.**
      - v1.**
      - v2.**
    #branches-ignore:
    #  - 'releases/**-alpha'
    #tags-ignore:
    #  - v999.**
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build miniscript-docker image'
            run: |
              docker build . --tag ghcr.io/bitcoincore-dev/miniscript-docker:latest
              docker push ghcr.io/bitcoincore-dev/miniscript-docker:latest
