name: publish to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
      - v**
    tags:
      - v0.**
      - v1.**
      - v2.**
    #branches-ignore:
    #  - 'releases/**-alpha'
    #tags-ignore:
    #  - v999.**
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: '.'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build miniscript-docker image'
            run: |
              docker build . --tag ghcr.io/bitcoincore-dev/miniscript-docker:latest
              docker push ghcr.io/bitcoincore-dev/miniscript-docker:latest
